version: 2

sources:
  - name: powerflow    # Name of the source referenced in the models
    database: powerflow
    schema: public
    tables:   # All of the tables referenced in the models
      - name: registrations_raw
      - name: appsflyer_raw
      - name: google_ads
      - name: transactions

models:
  - name: registrations_clean
    columns: 
      - name: user_id
        tests:
          - unique  # Checks if user_id is UNIQUE
  - name: marketing_attribution 
    columns: 
      - name: device_id
        tests:
          - unique  # Checks if device_id is UNIQUE and NOT NULL and so on...
          - not_null
      - name: attribution_cost
        tests:
          - not_null
  - name: ltv
    columns: 
      - name: reg_date
        tests:
            - not_null
      - name: transaction_date
        tests:
           - not_null
  - name: roi
    columns: 
      - name: attribution_cost
        tests:
            - not_null
      - name: roi
        tests:
           - not_null