version: 2

sources:
  - name: powerflow    # Name of the source referenced in the models
    database: powerflow
    schema: public
    tables:   # All of the tables referenced in the models
      - name: registrations_raw
      - name: appsflyer_raw
      - name: google_ads
      - name: transactions

models:
  - name: registrations_clean
    description: This model filters out users who haven't completed registrations (NULL values)
    columns: 
      - name: user_id
        tests:
          - unique  # Checks if user_id is UNIQUE
  - name: marketing_attribution
    description: Google and Appsflyer data merged.
    columns: 
      - name: device_id
        tests:
          - unique  # Checks if device_id is UNIQUE and NOT NULL and so on...
          - not_null
      - name: attribution_cost
        tests:
          - not_null
  - name: ltv
    description: This LTV table aggregates customer transaction data to compute Lifetime Value, based on purchases.
    columns: 
      - name: reg_date
        tests:
            - not_null
      - name: transaction_date
        tests:
           - not_null
  - name: roi
    description: Return of Investment table.
    columns: 
      - name: attribution_cost
        tests:
            - not_null
      - name: roi
        description: Calculated as ltv on a day devided by attribution_cost.
        tests:
           - not_null